// Generated by gencpp from file assignment_1/bumper.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_1_MESSAGE_BUMPER_H
#define ASSIGNMENT_1_MESSAGE_BUMPER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_1
{
template <class ContainerAllocator>
struct bumper_
{
  typedef bumper_<ContainerAllocator> Type;

  bumper_()
    : bumper(0)  {
    }
  bumper_(const ContainerAllocator& _alloc)
    : bumper(0)  {
  (void)_alloc;
    }



   typedef int32_t _bumper_type;
  _bumper_type bumper;





  typedef boost::shared_ptr< ::assignment_1::bumper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_1::bumper_<ContainerAllocator> const> ConstPtr;

}; // struct bumper_

typedef ::assignment_1::bumper_<std::allocator<void> > bumper;

typedef boost::shared_ptr< ::assignment_1::bumper > bumperPtr;
typedef boost::shared_ptr< ::assignment_1::bumper const> bumperConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_1::bumper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_1::bumper_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_1::bumper_<ContainerAllocator1> & lhs, const ::assignment_1::bumper_<ContainerAllocator2> & rhs)
{
  return lhs.bumper == rhs.bumper;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_1::bumper_<ContainerAllocator1> & lhs, const ::assignment_1::bumper_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1::bumper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1::bumper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1::bumper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1::bumper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1::bumper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1::bumper_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_1::bumper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d6f918bdf3f8c0d7fc9d69d24c5a14f";
  }

  static const char* value(const ::assignment_1::bumper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d6f918bdf3f8c0dULL;
  static const uint64_t static_value2 = 0x7fc9d69d24c5a14fULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_1::bumper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_1/bumper";
  }

  static const char* value(const ::assignment_1::bumper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_1::bumper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 bumper\n"
;
  }

  static const char* value(const ::assignment_1::bumper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_1::bumper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bumper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bumper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_1::bumper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_1::bumper_<ContainerAllocator>& v)
  {
    s << indent << "bumper: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bumper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_1_MESSAGE_BUMPER_H
