// Generated by gencpp from file assignment_1/laser.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_1_MESSAGE_LASER_H
#define ASSIGNMENT_1_MESSAGE_LASER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_1
{
template <class ContainerAllocator>
struct laser_
{
  typedef laser_<ContainerAllocator> Type;

  laser_()
    : processedRange()  {
    }
  laser_(const ContainerAllocator& _alloc)
    : processedRange(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _processedRange_type;
  _processedRange_type processedRange;





  typedef boost::shared_ptr< ::assignment_1::laser_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_1::laser_<ContainerAllocator> const> ConstPtr;

}; // struct laser_

typedef ::assignment_1::laser_<std::allocator<void> > laser;

typedef boost::shared_ptr< ::assignment_1::laser > laserPtr;
typedef boost::shared_ptr< ::assignment_1::laser const> laserConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_1::laser_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_1::laser_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_1::laser_<ContainerAllocator1> & lhs, const ::assignment_1::laser_<ContainerAllocator2> & rhs)
{
  return lhs.processedRange == rhs.processedRange;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_1::laser_<ContainerAllocator1> & lhs, const ::assignment_1::laser_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1::laser_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1::laser_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1::laser_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1::laser_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1::laser_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1::laser_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_1::laser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e307b89be484e2eb589951f9421237f0";
  }

  static const char* value(const ::assignment_1::laser_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe307b89be484e2ebULL;
  static const uint64_t static_value2 = 0x589951f9421237f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_1::laser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_1/laser";
  }

  static const char* value(const ::assignment_1::laser_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_1::laser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] processedRange\n"
;
  }

  static const char* value(const ::assignment_1::laser_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_1::laser_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.processedRange);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct laser_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_1::laser_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_1::laser_<ContainerAllocator>& v)
  {
    s << indent << "processedRange[]" << std::endl;
    for (size_t i = 0; i < v.processedRange.size(); ++i)
    {
      s << indent << "  processedRange[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.processedRange[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_1_MESSAGE_LASER_H
